/* Represents an error generated by the Client */
export class ClientError extends Error {
    /* The message of the error */
    message: string

    constructor(message: string) {
        super()

        this.message = message
    }
}